# These are supported funding model platforms

github: [willtheorangeguy]
custom: ['https://paypal.me/wvdg44', 'https://www.magazinesdirect.com/az-magazines/53604058/maximum-pc-magazine-subscription.thtml?j=MPC']
